/** 提示词定制面板各组件共享的内联样式（颜色走半透明灰，随宿主主题自然适配）。 */
export const s = (() => {
  const flex = { display: 'flex', alignItems: 'center' }
  return {
    // ── 面板骨架（抽屉内部分栏布局） ──────────────────────────────────
    pRoot: { height: '100%', display: 'flex', flexDirection: 'column', fontFamily: 'inherit', fontSize: 13, lineHeight: 1.5, minHeight: 0 },
    head: { ...flex, gap: 10, padding: '10px 14px 8px', flexWrap: 'wrap', borderBottom: '1px solid rgba(128,128,128,.18)' },
    headTitle: { ...flex, gap: 8, fontSize: 15, fontWeight: 600, whiteSpace: 'nowrap' },
    seg: { ...flex, gap: 2, padding: 2, border: '1px solid rgba(128,128,128,.28)', borderRadius: 8 },
    segBtn: { padding: '3px 12px', border: 'none', borderRadius: 6, background: 'transparent', cursor: 'pointer', color: 'inherit', opacity: 0.72, fontSize: 13, whiteSpace: 'nowrap' },
    segBtnActive: { padding: '3px 12px', border: 'none', borderRadius: 6, background: 'rgba(88,166,255,.22)', cursor: 'pointer', color: 'inherit', fontWeight: 600, fontSize: 13, whiteSpace: 'nowrap' },
    grow: { flex: 1, minWidth: 0 },
    headActions: { ...flex, gap: 6, marginLeft: 'auto' },
    iconBtn: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 28, height: 28, border: 'none', borderRadius: 8, background: 'transparent', cursor: 'pointer', color: 'inherit', opacity: 0.75 },
    subhead: { ...flex, gap: 8, padding: '8px 14px', flexWrap: 'wrap', borderBottom: '1px solid rgba(128,128,128,.14)' },
    targetRow: { ...flex, gap: 4, overflowX: 'auto', maxWidth: '100%', scrollbarWidth: 'thin' },
    targetTab: { ...flex, gap: 6, padding: '4px 12px', border: '1px solid rgba(128,128,128,.28)', borderRadius: 999, background: 'transparent', cursor: 'pointer', color: 'inherit', opacity: 0.78, fontSize: 12, whiteSpace: 'nowrap' },
    targetTabActive: { ...flex, gap: 6, padding: '4px 12px', border: '1px solid rgba(88,166,255,.65)', borderRadius: 999, background: 'rgba(88,166,255,.18)', cursor: 'pointer', color: 'inherit', fontWeight: 600, fontSize: 12, whiteSpace: 'nowrap' },
    body: { flex: 1, minHeight: 0, display: 'flex', alignItems: 'stretch' },
    colLeft: { width: 420, flex: 'none', display: 'flex', flexDirection: 'column', minHeight: 0, borderRight: '1px solid rgba(128,128,128,.18)', boxSizing: 'border-box' },
    colScroll: { flex: 1, minHeight: 0, overflowY: 'auto', padding: '10px 12px' },
    colFoot: { flex: 'none', ...flex, gap: 8, padding: '8px 12px', borderTop: '1px solid rgba(128,128,128,.18)', flexWrap: 'wrap' },
    colRight: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', minHeight: 0 },
    colRightScroll: { flex: 1, minHeight: 0, overflowY: 'auto', padding: '10px 14px' },
    groupHead: { ...flex, gap: 8, marginBottom: 6, color: 'rgba(128,128,128,.95)', fontSize: 12, fontWeight: 600 },
    // ── 通用控件（沿用旧面板的观感） ──────────────────────────────────
    list: { display: 'flex', flexDirection: 'column', gap: 6 },
    row: { ...flex, gap: 8, padding: '6px 8px', border: '1px solid rgba(128,128,128,.2)', borderRadius: 8, background: 'rgba(128,128,128,.06)' },
    switchWrap: { ...flex, gap: 6, minWidth: 90 },
    rowBody: { flex: 1, minWidth: 0 },
    rowTitle: { ...flex, gap: 6, alignItems: 'baseline', flexWrap: 'wrap' },
    code: { fontFamily: 'monospace', fontSize: 12, wordBreak: 'break-all' },
    orderTag: { color: 'rgba(128,128,128,.8)', fontSize: 11 },
    preview: { color: 'rgba(128,128,128,.85)', fontSize: 12, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
    previewText: { fontFamily: 'monospace', fontSize: 12, lineHeight: 1.6, whiteSpace: 'pre-wrap', wordBreak: 'break-word', flex: 1, minHeight: 0, overflowY: 'auto', padding: 10, border: '1px solid rgba(128,128,128,.2)', borderRadius: 8, background: 'rgba(0,0,0,.18)', margin: 0 },
    toolWrap: { display: 'flex', flexWrap: 'wrap', gap: 6 },
    toolChip: { fontFamily: 'monospace', fontSize: 12, color: 'rgba(128,128,128,.95)', border: '1px solid rgba(128,128,128,.3)', borderRadius: 6, padding: '2px 6px', cursor: 'help' },
    badgeOk: { color: '#3fb950', fontSize: 11, border: '1px solid rgba(63,185,80,.5)', borderRadius: 999, padding: '0 6px' },
    badgeBlocked: { color: '#f85149', fontSize: 11, border: '1px solid rgba(248,81,73,.5)', borderRadius: 999, padding: '0 6px' },
    badgeReplaced: { color: '#d29922', fontSize: 11, border: '1px solid rgba(210,153,34,.5)', borderRadius: 999, padding: '0 6px' },
    badgeCustom: { color: '#58a6ff', fontSize: 11, border: '1px solid rgba(88,166,255,.5)', borderRadius: 999, padding: '0 6px' },
    badgeSystem: { color: 'rgba(128,128,128,.85)', fontSize: 11, border: '1px solid rgba(128,128,128,.4)', borderRadius: 999, padding: '0 6px' },
    mini: { padding: '3px 8px', border: '1px solid rgba(128,128,128,.35)', borderRadius: 6, background: 'transparent', cursor: 'pointer', color: 'inherit', whiteSpace: 'nowrap' },
    arrowCol: { display: 'flex', flexDirection: 'column', gap: 2 },
    arrow: { padding: '0 6px', border: '1px solid rgba(128,128,128,.3)', borderRadius: 4, background: 'transparent', cursor: 'pointer', color: 'inherit', fontSize: 11, lineHeight: 1.4, opacity: 0.8 },
    rowBlocked: { opacity: 0.55 },
    injectBox: { marginTop: 10, padding: '8px', border: '1px dashed rgba(128,128,128,.4)', borderRadius: 8, display: 'flex', flexDirection: 'column', gap: 6 },
    injectRow: { ...flex, gap: 6 },
    editBox: { display: 'flex', flexDirection: 'column', gap: 6, marginTop: 4 },
    editInput: { padding: '6px', border: '1px solid rgba(128,128,128,.35)', borderRadius: 6, background: 'transparent', color: 'inherit', fontFamily: 'inherit', fontSize: 12, resize: 'vertical', width: '100%', boxSizing: 'border-box' },
    input: { padding: '4px 6px', border: '1px solid rgba(128,128,128,.35)', borderRadius: 6, background: 'transparent', color: 'inherit' },
    muted: { color: 'rgba(128,128,128,.75)', fontSize: 12 },
    error: { color: '#f85149', fontSize: 12, marginBottom: 6 },
    noticeOk: { color: '#3fb950', fontSize: 12, marginBottom: 6 },
    noticeWarn: { color: '#d29922', fontSize: 12, marginBottom: 6 },
    saveBtn: { padding: '4px 12px', border: '1px solid rgba(128,128,128,.35)', borderRadius: 6, background: 'transparent', cursor: 'pointer', color: 'inherit' },
    saveBtnDirty: { padding: '4px 12px', border: '1px solid #d29922', borderRadius: 6, background: 'rgba(210,153,34,.15)', cursor: 'pointer', color: 'inherit' },
  }
})()
